library(dplyr)

# NOTE: for the time being the functions are tested only vs the format generated
# by dump script

# 'load' returns a data.frame obtained by reading a csv file generated by the 
# dump script and removing all records whose description does not contain 
# 'filterDescriptionBy'. This is made necessary by the data potentially 
# referencing the search term in any other column 
load <- function(csvFilename, filterDescriptionBy) {
    d <- read.csv(csvFilename)
    records_matching_search_string_in_description(d, filterDescriptionBy)
}

records_matching_search_string_in_description <- function (d, searchString) {
    d[grep(searchString, d$description, ignore.case = TRUE), ]
}